[package]
name = "rustbpe"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustbpe"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module", "abi3-py310"] }
mpi = "0.8"
rayon = "1.10.0"
itertools = "0.12"
fancy-regex = "0.14"